<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFrameworks>net35;net40;net45;net47;net472;netcoreapp3.0;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks> 
    <!--<TargetFrameworks>net10.0</TargetFrameworks>-->

    <!--For UnitTesting the .NET Standard versions-->
    <!--<TargetFrameworks>netcoreapp2.0;netcoreapp3.0</TargetFrameworks>-->
    
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\KGySoft.snk</AssemblyOriginatorKeyFile>
    <RootNamespace>KGySoft.CoreLibraries</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>

    <!-- NUnit does not run .NET 3.5 tests on the correct runtime and .NET Core 2.0 tests at all so the tests for these targets can be executed as a console app -->
    <OutputType>Exe</OutputType>
    <GenerateProgramFile>false</GenerateProgramFile>

    <IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>

    <!--Suppressions
      - MSB3825: Resources serialized by BinaryFormatter that will be removed in .NET 9 - intended, test data, and used when targeting .NET Framework
      - NETSDK1138: The target framework 'tfm' is out of support - this is not an application but a library so targeting the lowest possible versions is intended
      -->
    <NoWarn>$(NoWarn);MSB3825;NETSDK1138</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\TestResourceResX.resx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <!--Required to avoid MSB3822 on non-Windows platforms-->
  <PropertyGroup Condition="'$(IsWindows)'!='true'">
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <!-- Project references -->
  <ItemGroup>
    <ProjectReference Include="..\KGySoft.CoreLibraries\KGySoft.CoreLibraries.csproj" />
  </ItemGroup>

  <!-- Common NuGet references -->
  <ItemGroup>
    <!--NUnit 4.x has major breaking changes and does not support Framework 4.6.2- and .NET 6-. -->
    <PackageReference Include="NUnit" Version="3.14" />

    <!-- Cannot use different adapter versions for the different frameworks, because the Test Explorer chooses the highest version for all platforms (even though build works).
         6.0.0 works with .NET Framework 4.6.2 and .NET 8+ only 
         5.2.0 Emits an error for .NET Core 3.0-
         3.15.1 Would work even with .NET Core 2.0, but Visual Studio is no longer compatible with it
         ==> Using 5.1.0. Though it compiles for all targets, executing .NET Core 2.x/3.0 tests is no longer supported from the Test Explorer.
             Execute .NET Framework 3.5 and .NET Core 2.x/3.x tests as a console application. -->
    <PackageReference Include="NUnit3TestAdapter" Version="5.1.0">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
  </ItemGroup>

  <!-- .NET Framework 4.x only references -->
  <ItemGroup Condition="'$(TargetFramework)'=='net40' OR '$(TargetFramework)'=='net45' OR '$(TargetFramework)'=='net47' OR '$(TargetFramework)'=='net472' OR '$(TargetFramework)'=='net48'">
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <!-- Microsoft.NET.Test.Sdk -->
  <ItemGroup Condition="'$(TargetFramework)'=='net47' OR '$(TargetFramework)'=='net472' OR '$(TargetFramework)'=='net8.0' OR '$(TargetFramework)'=='net9.0' OR '$(TargetFramework)'=='net10.0'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1"/>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net35' OR '$(TargetFramework)'=='net40' OR '$(TargetFramework)'=='net45' OR '$(TargetFramework)'=='netcoreapp2.0' OR '$(TargetFramework)'=='netcoreapp2.1' OR '$(TargetFramework)'=='netcoreapp3.0' OR '$(TargetFramework)'=='net5.0' OR '$(TargetFramework)'=='net6.0' OR '$(TargetFramework)'=='net7.0'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0"/>
  </ItemGroup>

  <!-- System.Resources.Extensions. Required for non-string resources. On .NET Framework it is required on non-Windows platforms only, where it requires at least net462. -->
  <ItemGroup Condition="'$(TargetFramework)'=='net47' OR '$(TargetFramework)'=='net472'">
    <PackageReference Condition="'$(IsWindows)'!='true'" Include="System.Resources.Extensions" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0' OR '$(TargetFramework)' == 'net9.0' OR '$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="System.Resources.Extensions" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0' OR '$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.0' OR '$(TargetFramework)' == 'net5.0'">
    <PackageReference Include="System.Resources.Extensions" Version="5.0.0" />
  </ItemGroup>

</Project>
